FROM ubuntu:22.04
FROM ubuntu:22.04

WORKDIR /app

RUN apt update && apt install -y python3 python3-pip
RUN pip3 install bandit

COPY app/ app/
COPY security/ security/

RUN chmod +x security/scan.sh

CMD ["./security/scan.sh"z
