name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t devsecops-secure .

      - name: Ejecutar Bandit
        run: docker run devsecops-secure

      - name: Instalar Trivy
        run: |
          sudo apt update
          sudo apt install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy

      - name: Escanear imagen
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL devsecops-secure
